# Generated by Django 6.0.6 on 2026-07-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('tipo', models.CharField(choices=[('ROPA', 'Ropa Deportiva / Casual'), ('CALZADO', 'Calzado (Tenis, Tacos, Burros)'), ('ACCESORIO', 'Accesorios (Lociones, Fajas, Otros)')], max_length=20, verbose_name='Tipo de Producto')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en Inventario')),
                ('talla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla / Tamaño (Opcional)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca')),
            ],
        ),
    ]
