# Generated by Django 6.0.6 on 2026-07-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '➕ Entrada (Compra / Reabastecimiento)'), ('SALIDA', '➖ Salida (Venta / Ajuste)')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(help_text='Ej: Venta de mostrador, Compra a proveedor', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
        ),
    ]
